version: '3.9'
services:
  postgresql:
    build:
      context: ./sql
    ports:
      - '6543:5432'
    environment:
      POSTGRES_DB: dockerDB
      POSTGRES_PASSWORD: admin
    depends_on:
      - broker
  fastapi1:
    build:
      context: ./api
    ports:
      - '8001:8000'
    depends_on:
      - postgresql
  fastapi2:
    build:
      context: ./api
    ports:
      - '8002:8000'
    depends_on:
      - postgresql
  nginx:
    build:
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - fastapi1
      - fastapi2
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.3.0'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: 'confluentinc/cp-kafka:7.3.0'
    ports:
      - '9092:9092'
    expose:
      - '29092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    networks:
      default:
        ipv4_address: 172.22.0.4
    command: sh -c "((sleep 15 && kafka-topics --bootstrap-server localhost:29092 --create --if-not-exists --topic database)&) && /etc/confluent/docker/run ">

networks:
  default:
    name: customNetwork
    ipam:
      config:
        - subnet: "172.22.0.0/24"