version: '3.9'
services:
  postgresql:
    build:
      context: ./sql
    ports:
      - '6543:5432'
    environment:
      POSTGRES_DB: dockerDB
      POSTGRES_PASSWORD: admin
  fastapi1:
    build:
      context: ./api
    ports:
      - '8001:8000'
    depends_on:
      - postgresql
  fastapi2:
    build:
      context: ./api
    ports:
      - '8002:8000'
    depends_on:
      - postgresql
  nginx:
    build:
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      - fastapi1
      - fastapi2

networks:
  default:
    name: customNetwork
    ipam:
      config:
        - subnet: "172.22.0.0/24"